In [1]:
import pandas as pd
from sqlalchemy import create_engine

C:\Users\Acer\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\Acer\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

In [2]:
engine = create_engine('postgresql+psycopg2://postgres:n9russin9arabic@localhost:5432/dunnhumby_mar_retail')

In [3]:
coupon = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/coupon.csv', sep=',', on_bad_lines='skip')
coupon_redempt = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/coupon_redempt.csv', sep=',', on_bad_lines='skip')
hh_demographic = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/hh_demographic.csv', sep=',', on_bad_lines='skip')
product = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/product.csv', sep=',', on_bad_lines='skip')
campaign_desc = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/campaign_desc.csv', sep=',', on_bad_lines='skip')
campaign_table = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/campaign_table.csv', sep=',', on_bad_lines='skip')

In [25]:
causal_data = pd.read_csv('C:/Users/Acer/Downloads/dunnhumby/causal_data.csv',  
                  dtype={
                        'store_id': 'int32',
                      'week_no': 'int16',
                      'product_id': 'int32',
                  },
                  sep=',', on_bad_lines='skip')

In [26]:
causal_data.head(5)

   PRODUCT_ID  STORE_ID  WEEK_NO display mailer
0       26190       286       70       0      A
1       26190       288       70       0      A
2       26190       289       70       0      A
3       26190       292       70       0      A
4       26190       293       70       0      A

In [34]:
causal_data.tail(5)

          PRODUCT_ID  STORE_ID  WEEK_NO display mailer
36786519    18203921       439      100       1      0
36786520    18203921       439      101       1      0
36786521    18243471       415      101       3      0
36786522    18243476       415      101       3      0
36786523    18244453       345      101       7      0

In [35]:
causal_data.dtypes

PRODUCT_ID     int64
STORE_ID       int64
WEEK_NO        int64
display       object
mailer        object
dtype: object

In [36]:
causal_data.count()

PRODUCT_ID    36786524
STORE_ID      36786524
WEEK_NO       36786524
display       36786524
mailer        36786524
dtype: int64

In [37]:
causal_data = causal_data.drop_duplicates()

In [38]:
causal_data.count()

PRODUCT_ID    36786524
STORE_ID      36786524
WEEK_NO       36786524
display       36786524
mailer        36786524
dtype: int64

In [27]:
transaction_data.head(5)

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0

In [28]:
coupon.head(5)

    COUPON_UPC  PRODUCT_ID  CAMPAIGN
0  10000089061       27160         4
1  10000089064       27754         9
2  10000089073       28897        12
3  51800009050       28919        28
4  52100000076       28929        25

In [29]:
coupon_redempt.head(5)

   household_key  DAY   COUPON_UPC  CAMPAIGN
0              1  421  10000085364         8
1              1  421  51700010076         8
2              1  427  54200000033         8
3              1  597  10000085476        18
4              1  597  54200029176        18

In [30]:
hh_demographic.head(5)

,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,household_key
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16

In [31]:
product.head(5)

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [32]:
campaign_desc.head(5)

  DESCRIPTION  CAMPAIGN  START_DAY  END_DAY
0       TypeB        24        659      719
1       TypeC        15        547      708
2       TypeB        25        659      691
3       TypeC        20        615      685
4       TypeB        23        646      684

In [33]:
campaign_table.head(5)

  DESCRIPTION  household_key  CAMPAIGN
0       TypeA             17        26
1       TypeA             27        26
2       TypeA            212        26
3       TypeA            208        26
4       TypeA            192        26

In [4]:
with engine.connect() as conn:
    coupon.to_sql('coupon', conn, if_exists='replace', index=False)
    coupon_redempt.to_sql('coupon_redempt', conn, if_exists='replace', index=False)
    hh_demographic.to_sql('hh_demographic', conn, if_exists='replace', index=False)
    product.to_sql('product', conn, if_exists='replace', index=False, chunksize=10000)
    campaign_desc.to_sql('campaign_desc', conn, if_exists='replace', index=False)
    campaign_table.to_sql('campaign_table', conn, if_exists='replace', index=False)

print("Done", len(coupon), "row loaded")

Done 124548 row loaded